---
kind: Pod
apiVersion: v1
metadata:
  name: testpod1
spec:
  containers:
    - name: coo
      image: httpd
      ports:
        - containerPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: testpod2
spec:
  containers:
    - name: c01
      image: httpd
      ports:
        - containerPort: 80
