---
kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: testpod
  labels:
   name: Shashank
   Tesla: Owner
   Meta: CEO
   Apple: CTO
   Amazon: CEO                  
spec:                                    
  containers:                      
    - name: c00                     
      image: httpd              
      ports:
       - containerPort: 80
  restartPolicy: Never

---
